sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5tPeFLzsPPT8gG3LPW64
    access-key-secret: U6k1brOZ8gaOIXv3nXbulGTUzy6Pd7
    bucket-name: sky-take-out
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: DB1
  wechat:
    appid: wx2eda51a8dca7ae40  # 确保这个appid正确
    secret: 914b9b9d3ef54277f2197164f5f98973  # 确保这个secret正确
    mchid: your_mchid_here
    mchSerialNo: your_mch_serial_no_here
    privateKeyFilePath: your_private_key_file_path_here
    apiV3Key: your_api_v3_key_here
    weChatPayCertFilePath: your_wechat_pay_cert_file_path_here


  shop:
    address: 北京市朝阳区某某街道

  baidu:
    ak: your_baidu_ak_here